### ISSUE TITLE
Update windows compilers

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/pyinterp-feedstock#97]
Hey all

This feedstock is directly specifying `vs2017_win-64` as a dependency,
https://github.com/conda-forge/pyinterp-feedstock/blob/f71f9cc6858b05c64eb75b437b01bfdb50beafeb/recipe/meta.yaml#L51-L57

but should just rely on the `{{ compiler('c') }}` function to provide the correct compilers on windows. In particular, conda-forge has moved on to vs2019 as the default compiler a while ago already.

If you think you need vs2017, please let us know why (generally vs2019 and vs2022 should be fully compatible). If it's really necessary, please use the dedicated mechanism in `conda_build_config.yaml` for that, i.e.
```
c_compiler:     # [win]
  - vs2017      # [win]
cxx_compiler:   # [win]
  - vs2017      # [win]
```
as opposed to specifying it in `meta.yaml` directly.

**Comment by fbriol** [comment]
The latest version 2024.1.0 takes this change into account.

**Comment by h-vetinari** [comment]
Thanks for the quick response! Just be aware that #98 did not yet rerender the feedstock after changing the compiler setup, so it'll probably pull in vs2022 currently, rather than the default vs2019
